### ISSUE TITLE
Add Navbar

### ISSUE THREAD

**Issue by ashwin3005** [TaufeeqRiyaz/Spotify-Clone#1]
Can I add a Navbar to this?

**Comment by dynamicashuu** [comment]
can i add a navbar to this ?

**Comment by 0xtaufeeq** [comment]
> Can I add a Navbar to this?


sure

**Comment by 0xtaufeeq** [comment]
> can i add a navbar to this ?


sure

**Comment by dynamicashuu** [comment]
`<div class="topnav">
  <a class="active" href="#home">Home</a>
  <a href="#recent">News</a>
  <a href="#playlist">Contact</a>
  <a href="#downloads">About</a>
 #</div>` # #
