### ISSUE TITLE
Adding new sections like Popular new releases , Focus ,Mood

### ISSUE THREAD

**Issue by dheeraj-singh-github** [TaufeeqRiyaz/Spotify-Clone#12]

**Comment by dheeraj-singh-github** [comment]
@TaufeeqRiyaz Hello, i want to add new sections in your spotify webpage. Can i contribute?

**Comment by 0xtaufeeq** [comment]
> @TaufeeqRiyaz Hello, i want to add new sections in your spotify webpage. Can i contribute?

Sure you can, if you want to do it, let me know, I'll assign this to you

**Comment by dheeraj-singh-github** [comment]
@TaufeeqRiyaz yes please assign it to me

**Comment by 0xtaufeeq** [comment]
> @TaufeeqRiyaz yes please assign it to me

@dheeraj-singh-github done!

**Comment by dheeraj-singh-github** [comment]
@TaufeeqRiyaz  PR sent
