### ISSUE TITLE
Full screen view button

### ISSUE THREAD

**Issue by Aniket1026** [TaufeeqRiyaz/Spotify-Clone#13]
In the footer along with the volume range option we can add a full screen view button. As the clone is still static the image is static as of now but as the clone will become dynamic we can select what to show when full screen view is clicked.

The change look likes this : 

<img width="279" alt="spotify footer" src="https://user-images.githubusercontent.com/92184189/194382508-562323df-39e8-421c-aceb-6c829cd03ab5.PNG">

**Comment by 0xtaufeeq** [comment]
thank you the feedback, do you wanna work on this?

**Comment by Aniket1026** [comment]
Actually yes , I can raise a PR for this 😄

**Comment by 0xtaufeeq** [comment]
> Actually yes , I can raise a PR for this 😄

I've assigned this to you 😃
