### ISSUE TITLE
Search Bar in search.html

### ISSUE THREAD

**Issue by 0xtaufeeq** [TaufeeqRiyaz/Spotify-Clone#22]

**Comment by deven-533** [comment]
Can I take up this issue

**Comment by 0xtaufeeq** [comment]
> Can I take up this issue

Sure, I'll assign this to you

**Comment by Harikrishna3** [comment]
I'd like to work on this
Would you kindly assign it to me?

**Comment by 0xtaufeeq** [comment]
> I'd like to work on this Would you kindly assign it to me?

Sure, I'll assign this to you as well

**Comment by Adarsh-k0802** [comment]
@TaufeeqRiyaz  Can i work on this issue?
