### ISSUE TITLE
Recent Searches in search.html

### ISSUE THREAD

**Issue by 0xtaufeeq** [TaufeeqRiyaz/Spotify-Clone#25]
![image](https://user-images.githubusercontent.com/74425589/194491276-37eaff27-6f96-4ec5-a779-31c52dc7818e.png)

**Comment by Adarsh-k0802** [comment]
@TaufeeqRiyaz please assign this to me

**Comment by 0xtaufeeq** [comment]
> @TaufeeqRiyaz please assign this to me

Assigned!

**Comment by Adarsh-k0802** [comment]
done
