### ISSUE TITLE
Change cursor while hovering over "See all" to hand.

### ISSUE THREAD

**Issue by nihshesh** [TaufeeqRiyaz/Spotify-Clone#30]
Hi, I want to change the cursor type to hand and underline the "See all" present in the homepage while hovering over it.

**Comment by 0xtaufeeq** [comment]
> Hi, I want to change the cursor type to hand and underline the "See all" present in the homepage while hovering over it.

sure, I'll assign this to you!

**Comment by 0xtaufeeq** [comment]
Could you also fix the position and size of "see all"

original - 
![image](https://user-images.githubusercontent.com/74425589/194522120-c27fdfda-45e7-4dc3-bafb-a0c6e9a9d638.png)

clone -
![image](https://user-images.githubusercontent.com/74425589/194522168-92e2ee88-2e49-4589-a6f0-da58ad90eb5c.png)

**Comment by nihshesh** [comment]
Sure I will.
