### ISSUE TITLE
Adding shadow and hover zoom to play button

### ISSUE THREAD

**Issue by ArnavGuptaaa** [TaufeeqRiyaz/Spotify-Clone#31]
Hello, I would like to add a box shadow and a hover effect to the play button which shows up on playlists and songs

## Spotify
![image](https://user-images.githubusercontent.com/67139196/194527256-4fb2c967-c0fb-475c-a585-321848631ca1.png)

## Clone
![image](https://user-images.githubusercontent.com/67139196/194527153-03aa0857-1b11-436a-850e-831393284736.png)

**Comment by 0xtaufeeq** [comment]
Sure! I'll assign this to you
