### ISSUE TITLE
Fixing the rounding at the bottom of recently played cards

### ISSUE THREAD

**Issue by h3nrey** [TaufeeqRiyaz/Spotify-Clone#33]
Hello, I would like to fix the rounding of the recently played card, so that all the corners would be rounded correctly

**Original**
![image](https://user-images.githubusercontent.com/56360819/194559720-e3fc2f33-6161-4f6c-a00b-acf0f83ba0bf.png)

**Clone**
![image](https://user-images.githubusercontent.com/56360819/194559940-3318d4d9-bdf2-463a-bed5-265a97d02d76.png)

**Comment by 0xtaufeeq** [comment]
Hey @h3nrey I've assigned this to you, happy codding :)
