### ISSUE TITLE
Fixing the navigation bar

### ISSUE THREAD

**Issue by Utsab5** [TaufeeqRiyaz/Spotify-Clone#36]
**Describe the bug**
On scrolling, the navigation bar remains transparent and does not change to a solid color like in the original website.

**To Reproduce**
1. Go to 'the spotify clone website'
2. Scroll down 
3. See error

**Expected behavior**
I expect the nav bar to change its color to a solid color (like black)

**Screenshots**
Original
![sendtemp](https://user-images.githubusercontent.com/92643166/194637811-5240636b-3c5a-415e-a699-74757e8c284d.PNG)

Clone
![sendtemp2](https://user-images.githubusercontent.com/92643166/194637915-020a273f-2ce3-407a-bcb8-df8aaa7024f8.PNG)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: chrome
 - Version: latest version

**Additional context**
I can work on this issue under HACKTOBERFEST, if you want :)

**Comment by 0xtaufeeq** [comment]
Sure, I'll assign this to you

**Comment by Utsab5** [comment]
@TaufeeqRiyaz 
Done.
Made a PR , please have a look.
