### ISSUE TITLE
Drop down menu when clicked on profile name (top right)

### ISSUE THREAD

**Issue by 0xtaufeeq** [TaufeeqRiyaz/Spotify-Clone#40]
The position of "log out" button is in the bottom left, which can be shifted to a drop-down menu, just like in the screenshot attached below.

![image](https://user-images.githubusercontent.com/74425589/194686288-eb5e8566-cede-4f96-ab25-5ca0d104b5e0.png)

**Comment by JawHawk** [comment]
@TaufeeqRiyaz  I can work on this issue, can you please assign it to me ?

**Comment by 0xtaufeeq** [comment]
> @TaufeeqRiyaz I can work on this issue, can you please assign it to me ?

@JawHawk  sure, I'll assign this to you

**Comment by rahulxdemon** [comment]
Hey Bro, Did you finished the drop-down menu🤔🤔??

**Comment by 0xtaufeeq** [comment]
> Hey Bro, Did you finished the drop-down menu🤔🤔??

@Rahul-Palamarthi do you wanna work on this?

**Comment by rahulxdemon** [comment]
Yes

**Comment by 0xtaufeeq** [comment]
> Yes

#### I have assigned this to you as well, happy coding :)

**Comment by SharmilaChoudhary** [comment]
hey @TaufeeqRiyaz  I would like to work on this issue please assign it to me

**Comment by 0xtaufeeq** [comment]
> hey @TaufeeqRiyaz I would like to work on this issue please assign it to me

Sure, I'll assign this to you

**Comment by Naveen-Nair** [comment]
@TaufeeqRiyaz Hey i'd like to work on this issue also, can you please assign it to me too?

**Comment by manishgupta416** [comment]
Can you assign to me?

**Comment by 0xtaufeeq** [comment]
@Naveen-Nair @manishgupta416 assigned!

**Comment by Naveen-Nair** [comment]
@TaufeeqRiyaz Hey! I've tried working on it... Could you review my PR (#52) ?
